// Vant 按需导入 (推荐)
import Vue from 'vue'
import { Button, Switch, Tabbar, TabbarItem, NavBar, Toast, Checkbox, CheckboxGroup, Search, Swipe, SwipeItem, Grid, GridItem, Icon, Lazyload, Rate } from 'vant'

Vue.use(Button)
Vue.use(Switch)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Icon)
Vue.use(Lazyload)
Vue.use(Rate)
